<a href="https://colab.research.google.com/github/strangestmahi/Fake-news-/blob/main/DataFrame_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "Name": ["Disney", "Princess", "prince", "colgate"],
    "Gender": ["Male", "Female", "Male", "Female"],
    "Age": [21, 21, 19, 20]
}

df = pd.DataFrame(data)

df

       Name  Gender  Age
0    Disney    Male   21
1  Princess  Female   21
2    prince    Male   19
3   colgate  Female   20

In [4]:
df = pd.get_dummies(df, columns=["Gender"], dtype=int)

df

       Name  Age  Gender_Female  Gender_Male
0    Disney   21              0            1
1  Princess   21              1            0
2    prince   19              0            1
3   colgate   20              1            0

In [5]:
df = df.drop("Name", axis=1)

df

   Age  Gender_Female  Gender_Male
0   21              0            1
1   21              1            0
2   19              0            1
3   20              1            0

In [6]:
arr = df.to_numpy()

arr

array([[21,  0,  1],
       [21,  1,  0],
       [19,  0,  1],
       [20,  1,  0]])

In [7]:
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimension:", arr.ndim)

Shape: (4, 3)
Size: 12
Dimension: 2

In [8]:
A = arr[:2, :]
B = arr[2:, :]

print("A:")
print(A)

print("B:")
print(B)

A:
[[21  0  1]
 [21  1  0]]
B:
[[19  0  1]
 [20  1  0]]

In [9]:
A + B

array([[40,  0,  2],
       [41,  2,  0]])

In [10]:
A * B

array([[399,   0,   1],
       [420,   1,   0]])

In [11]:
A - B

array([[2, 0, 0],
       [1, 0, 0]])

In [12]:
np.dot(A, B.T)

array([[400, 420],
       [399, 421]])

In [13]:
A.T

array([[21, 21],
       [ 0,  1],
       [ 1,  0]])

In [14]:
C = arr[:2, :2]

C

array([[21,  0],
       [21,  1]])

In [15]:
np.linalg.inv(C)

array([[ 0.04761905,  0.        ],
       [-1.        ,  1.        ]])